### PR TITLE
Add .travis.yml for CI

### PR DESCRIPTION
**Pull request by scls19fr**
It will be nice to add Continuous Integration with Travis.
See as PR a .travis.yml file for https://travis-ci.org/

### CODE REVIEW

**Comment by scls19fr** [comment]
It should help to fix https://github.com/leforestier/yattag/issues/18

**Comment by leforestier** [comment]
Excellent, thank you!

**Comment by scls19fr** [comment]
Next step is to log to Travis website and to create https://travis-ci.org/leforestier/yattag

After 1 commit you will see build status.

You can put a build status badge on your README.md like

[Build Status](https://travis-ci.org/leforestier/yattag)

using `[Build Status](https://travis-ci.org/leforestier/yattag)`

And other interesting step to achieve is to ensure code quality (code health) using http://www.landscape.io/ and to also put a badge

[Code Health](https://landscape.io/github/leforestier/yattag/master)

using `[Code Health](https://landscape.io/github/leforestier/yattag/master)`

**Comment by leforestier** [comment]
Thanks for the tip.

**Comment by scls19fr** [comment]
my pleasure!

**Pull request merged**
